USE [master]
GO
/****** Object:  Database [CDW]    Script Date: 16/02/2024 10:36:30 ******/
CREATE DATABASE [CDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CDW', FILENAME = N'/var/opt/mssql/data/CDW.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CDW_log', FILENAME = N'/var/opt/mssql/data/CDW_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [CDW] SET COMPATIBILITY_LEVEL = 160
GO
